package com.mewhpm.mewphotoprism.pojo

import com.google.gson.annotations.SerializedName

data class PhotoprismImage(
    @SerializedName("ID"           ) var ID           : String?          = null,
    @SerializedName("UID"          ) var UID          : String?          = null,
    @SerializedName("Type"         ) var Type         : String?          = null,
    @SerializedName("TypeSrc"      ) var TypeSrc      : String?          = null,
    @SerializedName("TakenAt"      ) var TakenAt      : String?          = null,
    @SerializedName("TakenAtLocal" ) var TakenAtLocal : String?          = null,
    @SerializedName("TakenSrc"     ) var TakenSrc     : String?          = null,
    @SerializedName("TimeZone"     ) var TimeZone     : String?          = null,
    @SerializedName("Path"         ) var Path         : String?          = null,
    @SerializedName("Name"         ) var Name         : String?          = null,
    @SerializedName("OriginalName" ) var OriginalName : String?          = null,
    @SerializedName("Title"        ) var Title        : String?          = null,
    @SerializedName("Description"  ) var Description  : String?          = null,
    @SerializedName("Year"         ) var Year         : Int?             = null,
    @SerializedName("Month"        ) var Month        : Int?             = null,
    @SerializedName("Day"          ) var Day          : Int?             = null,
    @SerializedName("Country"      ) var Country      : String?          = null,
    @SerializedName("Stack"        ) var Stack        : Int?             = null,
    @SerializedName("Favorite"     ) var Favorite     : Boolean?         = null,
    @SerializedName("Private"      ) var Private      : Boolean?         = null,
    @SerializedName("Iso"          ) var Iso          : Int?             = null,
    @SerializedName("FocalLength"  ) var FocalLength  : Int?             = null,
    @SerializedName("FNumber"      ) var FNumber      : Double?          = null,
    @SerializedName("Exposure"     ) var Exposure     : String?          = null,
    @SerializedName("Quality"      ) var Quality      : Int?             = null,
    @SerializedName("Resolution"   ) var Resolution   : Int?             = null,
    @SerializedName("Color"        ) var Color        : Int?             = null,
    @SerializedName("Scan"         ) var Scan         : Boolean?         = null,
    @SerializedName("Panorama"     ) var Panorama     : Boolean?         = null,
    @SerializedName("CameraID"     ) var CameraID     : Int?             = null,
    @SerializedName("CameraSerial" ) var CameraSerial : String?          = null,
    @SerializedName("CameraSrc"    ) var CameraSrc    : String?          = null,
    @SerializedName("CameraModel"  ) var CameraModel  : String?          = null,
    @SerializedName("CameraMake"   ) var CameraMake   : String?          = null,
    @SerializedName("LensID"       ) var LensID       : Int?             = null,
    @SerializedName("LensModel"    ) var LensModel    : String?          = null,
    @SerializedName("LensMake"     ) var LensMake     : String?          = null,
    @SerializedName("Lat"          ) var Lat          : Int?             = null,
    @SerializedName("Lng"          ) var Lng          : Int?             = null,
    @SerializedName("CellID"       ) var CellID       : String?          = null,
    @SerializedName("PlaceID"      ) var PlaceID      : String?          = null,
    @SerializedName("PlaceSrc"     ) var PlaceSrc     : String?          = null,
    @SerializedName("PlaceLabel"   ) var PlaceLabel   : String?          = null,
    @SerializedName("PlaceCity"    ) var PlaceCity    : String?          = null,
    @SerializedName("PlaceState"   ) var PlaceState   : String?          = null,
    @SerializedName("PlaceCountry" ) var PlaceCountry : String?          = null,
    @SerializedName("InstanceID"   ) var InstanceID   : String?          = null,
    @SerializedName("FileUID"      ) var FileUID      : String?          = null,
    @SerializedName("FileRoot"     ) var FileRoot     : String?          = null,
    @SerializedName("FileName"     ) var FileName     : String?          = null,
    @SerializedName("Hash"         ) var Hash         : String?          = null,
    @SerializedName("Width"        ) var Width        : Int?             = null,
    @SerializedName("Height"       ) var Height       : Int?             = null,
    @SerializedName("Portrait"     ) var Portrait     : Boolean?         = null,
    @SerializedName("Merged"       ) var Merged       : Boolean?         = null,
    @SerializedName("CreatedAt"    ) var CreatedAt    : String?          = null,
    @SerializedName("UpdatedAt"    ) var UpdatedAt    : String?          = null,
    @SerializedName("EditedAt"     ) var EditedAt     : String?          = null,
    @SerializedName("CheckedAt"    ) var CheckedAt    : String?          = null,
    @SerializedName("DeletedAt"    ) var DeletedAt    : String?          = null,
    @SerializedName("Files"        ) var Files        : ArrayList<PhotoprismImageFiles> = arrayListOf()
)
